### ISSUE TITLE
Fix issue with creating secret lock service

### ISSUE THREAD

**Issue by aholovko** [trustbloc/hub-kms#110]
Investigate and fix crash in AuthZ KMS when "secrets split lock" is used for multi-user scenario:

```
ERROR Failed to create a KMS service: failed to create new secret lock service: cipher: message authentication failed
```

**Comment by llorllale** [comment]
I just had this error and I worked around it by removing the volumes (`docker-compose rm -f -s- v) and restarting the containers.

If/when it happens next time I will ssh into the running container and inspect the contents of `secret-lock.key` and go from there.
