### ISSUE TITLE
Discuss project goals and features

### ISSUE THREAD

**Issue by aholovko** [trustbloc/hub-kms#4]

**Comment by aholovko** [comment]
Key Server (hub-kms) should:
- support OIDC/Auth flow
   - ability to login into Key Server with GoogleID, AppleID, etc.
   - similar to the one that is currently implementing in [edge-adapter](https://github.com/trustbloc/edge-adapter/issues/15)
   - [TODO] Investigate/consider if implementation can be shared between projects (discuss with @llorllale, @rolsonquadras)

- expose API for KMS operations
   - [TODO] Define a set of operations that should be supported for the initial phase (e.g. registering a keystore, generating keys, wrapping/unwrapping keys, etc.) (discuss with @troyronda, @llorllale)
   - [TODO] Investigate how the functionality of hub-kms correlates with [KMS API](https://github.com/hyperledger/aries-framework-go/blob/4dfa67ffc1765231286183aa33e018f4086bde80/pkg/kms/api.go#L18) and exposed [REST API](https://github.com/hyperledger/aries-framework-go/blob/4dfa67ffc1765231286183aa33e018f4086bde80/pkg/controller/rest/kms/operation.go#L63) (discuss with @Baha-sk)

**Comment by llorllale** [comment]
@aholovko 

> Investigate/consider if [OIDC] implementation can be shared between projects

Golang has a standard package for OAuth2, and there are a couple of libraries out there that extend it with OIDC capabilities. We're using `github.com/coreos/go-oidc` in edge-adapter.

**Comment by aholovko** [comment]
> @aholovko
> 
> > Investigate/consider if [OIDC] implementation can be shared between projects
> 
> Golang has a standard package for OAuth2, and there are a couple of libraries out there that extend it with OIDC capabilities. We're using `github.com/coreos/go-oidc` in edge-adapter.

Thanks @llorllale. I am also curious about that DAL and persistence regarding login that you are adding in edge-adapter implementation. Could you plz elaborate a bit on that?
